# Generated by Django 2.2.1 on 2019-06-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcat', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nomcat', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombrep', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipocambio',
            fields=[
                ('id_cambio', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombrecamp', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('idsubc', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nomsc', models.TextField(max_length=200)),
                ('idcat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedatos.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idreg', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombreg', models.TextField(max_length=200)),
                ('idpais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedatos.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Bienesyservicios',
            fields=[
                ('idbs', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombrebs', models.TextField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=5)),
                ('imgc', models.ImageField(upload_to='bysimg')),
                ('fuente', models.URLField()),
                ('fechas', models.DateField()),
                ('fechapub', models.DateField()),
                ('id_cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedatos.Tipocambio')),
                ('idreg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedatos.Region')),
                ('idsubc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basedatos.Subcategoria')),
            ],
        ),
    ]
