# Generated by Django 2.2.1 on 2019-06-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0002_auto_20190626_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bienesyservicios',
            options={'ordering': ['nombrebs'], 'verbose_name': 'Bienesyservicios', 'verbose_name_plural': 'Bienesyservicios'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['idcat'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['idpais'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['idreg'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'ordering': ['idcat'], 'verbose_name': 'Subcategoria', 'verbose_name_plural': 'Subcategorias'},
        ),
        migrations.AlterModelOptions(
            name='tipocambio',
            options={'ordering': ['id_cambio'], 'verbose_name': 'Tipocambio', 'verbose_name_plural': 'Tipocambio'},
        ),
        migrations.AlterField(
            model_name='bienesyservicios',
            name='fechapub',
            field=models.DateField(verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='bienesyservicios',
            name='fechas',
            field=models.DateField(verbose_name='Fecha de scraping'),
        ),
        migrations.AlterField(
            model_name='bienesyservicios',
            name='idbs',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID bien y servicio'),
        ),
        migrations.AlterField(
            model_name='bienesyservicios',
            name='nombrebs',
            field=models.TextField(max_length=250, verbose_name='Nombre servicio'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nomcat',
            field=models.TextField(max_length=200, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='idpais',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pais'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombrep',
            field=models.TextField(max_length=200, verbose_name='Nombre Pais'),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombreg',
            field=models.TextField(max_length=200, verbose_name='Nombre Region'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nomsc',
            field=models.TextField(max_length=200, verbose_name='Subcategoria'),
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='nombrecamp',
            field=models.TextField(max_length=20, verbose_name='Moneda'),
        ),
    ]
